Update Kurtosis Docs for Environment Management Positioning
kurtosis-tech/kurtosis-tech.github.io pull request #50
Opened 2022-06-07 16:28 UTC by galenmarchetti

2022-06-07 18:30 UTC, amirrustam requested changes
Made some minor suggestions. We obviously can do more refactoring here, but I understand these are just quick and sufficient updates for now.

2022-06-07 18:30 UTC, amirrustam commented on index.md
> +Kurtosis is designed to optimize **environment** management and control across the development cycle - operating at one level of abstraction higher than existing tools, giving developers the environm
```suggestion
Kurtosis is designed to optimize **environment** management and control across the development cycle - operating at one level of abstraction higher than existing tools, giving developers the environments and the ability to manipulate them as needed at each stage.
```

2022-06-07 18:30 UTC, amirrustam commented on index.md
> +[Kurtosis](https://www.kurtosistech.com) is a platform for orchestrating distributed system environments, allowing easy creation and manipulation of stage-appropriate deployments across the developme
I am hesitant to say "across the development cycle" since we currently don't have an offering for the production stage.

2022-06-07 20:15 UTC, amirrustam approved these changes

2022-06-09 21:43 UTC, mieubrisse approved these changes
approved pending minor comments

2022-06-09 21:43 UTC, mieubrisse commented on index.md
> +[Kurtosis](https://www.kurtosistech.com) is a platform for orchestrating distributed system environments, allowing easy creation and manipulation of stage-appropriate deployments across in the early
typo "across in"

2022-06-09 21:43 UTC, mieubrisse commented on index.md
> +* Enable individual developers to prototype on personal development environments without messing with environment setup and configuration
can we s/messing/bothering? I've been tryign to keep a more formal/professional tone in the docs

2022-06-09 21:43 UTC, mieubrisse commented on index.md
> +With Kurtosis, developers can build with local sandbox environments that really demonstrate how their code will work when integrated with the rest of the system. In addition, advanced end-to-end test
what about s/really demonstrate/demonstrate/ for same reason as above?

2022-06-21 04:35 UTC, mieubrisse commented
Approved pending comments @galenmarchetti

2022-07-13 05:04 UTC, tedim52 approved these changes
LGTM, just made a few suggestions.

2022-07-13 05:04 UTC, tedim52 commented on index.md
> +
This last sentence is a large/general claim at a causal relationship, that relationship being "docker/kubernetes capabilities are limited" because of "their design". I feel like to make it, requires an explanation that isn't suited for this text, which is why I suggest omitting it. I think the sentence ends well on "incurring a massive amount of maintenance burden." as well.

2022-07-13 05:04 UTC, tedim52 commented on index.md
> +Container management and container orchestration systems like Docker and Kubernetes are each great at serving developers in different parts of the development cycle (development for Docker, productio
What do you think about "low-level, stage-specific tools that require..."? The  "and" breaks the flow a tinnny bit.

2022-08-01 22:16 UTC, galenmarchetti commented on index.md
> +
this is a good point. removed

2022-08-01 22:21 UTC, galenmarchetti commented on index.md
> +Container management and container orchestration systems like Docker and Kubernetes are each great at serving developers in different parts of the development cycle (development for Docker, productio
i like it, implemented

2022-08-01 22:29 UTC, merged